### ISSUE TITLE
results are different for a given simple example  

### ISSUE THREAD

**Issue by prhjiajie** [empymod/empymod#1]
Hi Dieter Werthmüller,
Very nice work. When I run a simple example given in model.py:
```
import numpy as np
from empymod import dipole
src = [0, 0, 100]
rec = [np.arange(1, 11)*500, np.zeros(10), 200]
depth = [0, 300, 1000, 1050]
res = [1e20, .3, 1, 50, 1]
EMfield = dipole(src, rec, depth, res, freqtime=1, verb=0)
print(EMfield)
```
The results are
```
[  4.58713929e-11 -1.71360411e-10j  -6.97266213e-12 -1.00555912e-12j
   2.57717900e-14 +4.99252420e-13j   4.36445152e-14 -1.20355003e-14j
  -2.23112374e-15 -4.12011680e-15j  -3.93535170e-16 +3.51191751e-16j
   5.16764963e-17 +3.58827958e-17j   2.82917050e-18 -7.29853500e-18j
  -9.97105343e-19 -1.31771731e-19j   1.42759606e-20 +1.31775378e-19j]
```
, which are not the same with the results 
```
[  1.68809346e-10 -3.08303130e-10j  -8.77189179e-12 -3.76920235e-11j
  -3.46654704e-12 -4.87133683e-12j  -3.60159726e-13 -1.12434417e-12j
    1.87807271e-13 -6.21669759e-13j   1.97200208e-13 -4.38210489e-13j
    1.44134842e-13 -3.17505260e-13j   9.92770406e-14 -2.33950871e-13j
    6.75287598e-14 -1.74922886e-13j   4.62724887e-14 -1.32266600e-13j]
```
given in model.py.  Did I get something wrong? Many thanks. 

FYI, the OS is windows 7 (64 bit).

**Comment by prisae** [comment]
Hi Ronghua,

Thanks for reporting. I am very interested in your feedback, as I never used empymod on Windows/Mac.

Could you provide me with some more information: version of empymod, numpy, scipy, and information how numpy was compiled. You can run the following lines and paste the output here:

    import numpy
    import scipy
    import empymod
    print("empymod :: %s" % empymod.__version__)
    print("numpy   :: %s" % numpy.__version__)
    print("scipy   :: %s" % scipy.__version__)
    print(numpy.show_config())

Also, what do you use to run it? A Python console, IPython console, or a Jupyter notebook?

How did you install it? From GitHub, PyPi, or conda?

Thanks,
Dieter

**Comment by prhjiajie** [comment]
Hi Dieter,

Thanks for your prompt attention. I installed the **empymod** package from PyPi and run the code snippets above in a Jupyter notebook. The output is
```
empymod :: v1.4.2.dev
numpy   :: 1.12.1
scipy   :: 0.19.0
lapack_opt_info:
    libraries = ['mkl_core_dll', 'mkl_intel_lp64_dll', 'mkl_intel_thread_dll']
    library_dirs = ['C:/Anaconda2\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Anaconda2\\Library\\include']
blas_opt_info:
    libraries = ['mkl_core_dll', 'mkl_intel_lp64_dll', 'mkl_intel_thread_dll']
    library_dirs = ['C:/Anaconda2\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Anaconda2\\Library\\include']
lapack_mkl_info:
    libraries = ['mkl_core_dll', 'mkl_intel_lp64_dll', 'mkl_intel_thread_dll']
    library_dirs = ['C:/Anaconda2\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Anaconda2\\Library\\include']
blas_mkl_info:
    libraries = ['mkl_core_dll', 'mkl_intel_lp64_dll', 'mkl_intel_thread_dll']
    library_dirs = ['C:/Anaconda2\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Anaconda2\\Library\\include']
None
```
Thanks,
Ronghua

**Comment by prisae** [comment]
From the output it looks like you're use Python 2 (`C:/Anaconda2`). I never tested Python 2, and various things definitely won't work with Python 2. Could you install Python 3, and check if it works with that? (As it is a new module I found there is no reason in supporting Python 2, as Python 2 support is doomed to end within a few years.)

Also, you have `scipy 0.19.0` installed. This version of SciPy has a bug in QUAD, so you might run into memory issues with it (see https://github.com/scipy/scipy/pull/7216)

Have a look at [Installation & requirements](https://empymod.github.io/#installation--requirements---), where the Python version and also the issue with SciPy are mentioned.

Question on the side: Did you really install it via `PyPi`? You're version `empymod :: v1.4.2.dev` indicates that you installed it from GitHub. If you did install it via `PyPi` then I'll have to check the version numbering, as there shouldn't be a `dev` in a PyPi-release...

Please let me know if it works!

**Comment by prhjiajie** [comment]
Thanks so much, Dieter. Yes, you are right. I got mixed up for the installation because the first installation via PyPi failed, then I had to install the package directly from the source code.   

Following the instructions, I will test how it goes using Python 3.

**Comment by prisae** [comment]
No problem at all. I guess the installation via PyPi failed because of the Python2-issue. If you are using Anaconda (Anaconda3!) then the best way is definitely

    conda install -c prisae empymod

and then make sure SciPy is at 0.18.1 with

    conda install scipy==0.18.1

I hope they release 0.19.1 soon, so the problem goes away.

Please let me know if you succeed with Python3. I keep the issue open until you confirm that it works for you now!

**Comment by prhjiajie** [comment]
Hi Dieter. following your instruction, I updated the Python to 3.6 and installed the package **empymod** via conda. Now all tests work as expected :+1: . The configuration information is 
```
empymod :: v1.4.2
numpy   :: 1.12.1
scipy   :: 0.18.1
blas_mkl_info:
    libraries = ['mkl_core_dll', 'mkl_intel_lp64_dll', 'mkl_intel_thread_dll']
    library_dirs = ['C:/Anaconda2/envs/py36\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Anaconda2/envs/py36\\Library\\include']
blas_opt_info:
    libraries = ['mkl_core_dll', 'mkl_intel_lp64_dll', 'mkl_intel_thread_dll']
    library_dirs = ['C:/Anaconda2/envs/py36\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Anaconda2/envs/py36\\Library\\include']
lapack_mkl_info:
    libraries = ['mkl_core_dll', 'mkl_intel_lp64_dll', 'mkl_intel_thread_dll']
    library_dirs = ['C:/Anaconda2/envs/py36\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Anaconda2/envs/py36\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_core_dll', 'mkl_intel_lp64_dll', 'mkl_intel_thread_dll']
    library_dirs = ['C:/Anaconda2/envs/py36\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Anaconda2/envs/py36\\Library\\include']
None
```
Thanks!

**Comment by prisae** [comment]
Great, glad it works now!

Don't hesitate to come back if there arises any other issue.
