### ISSUE TITLE
check_dipole fails for dipole with orientation

### ISSUE THREAD

**Issue by TobiasGlaubach** [empymod/empymod#100]
Hi,
first of all: Thanks for the amazing library and all the work you put into making it :-)

# Description:
I am facing some issues with non major aligned dipole sources. When I supply a azimuth and dip parameter as stated in the [API reference](https://empymod.readthedocs.io/en/stable/modeller.html) `check_dipole(...)` fails, because it expects `(x, y, z)` instead of the supplied `(x, y, z, azim, dip)`.

# Code to reproduce:

```python
import empymod
import numpy as np

sigma_h = np.r_[1, 0.55, 1]     # [S/m] Layer conductivities horizontal direction
sigma_v = np.r_[1, 0.18182, 1]  # [S/m] Layer conductivities vertical direction

depth = np.r_[5, 10] * 0.3048 # [m] Layer boundaries
aniso = sigma_v / sigma_h     # [ ] Layer anis. 
res = 1 / sigma_h             # [Ohm m] layer resistivity

# Modelling parameters
verb = 0
comp = 'H_zz'
ab = 66         # source and receiver z-directed

# Tool Parameters
freq = 20000        # [Hz] tool operation frequency
z_0 = 1             # [m] tool position
L = 40 * (2.54/100) # [m] distance between source and receiver
azim = 0            # [°] horizontal deviation from x-axis, anti-clockwise
dip = 60            # [°] vertical deviation from xy-plane down/up-wards

# Spatial parameters
p_src = [0, 0, z_0,     azim, dip]
p_rec = [0, 0, z_0 - L, azim, dip]

inpdat = {'src': p_src, 
          'rec': p_rec, 
          'depth': depth,
          'freqtime': freq, 
          'aniso': aniso, 
          'ab': ab,
          'htarg': {
              'pts_per_dec': -1
              }, 
          'verb': verb}

fEM = empymod.dipole(**inpdat, res=res)
print(f'   {comp} (real, imag) {fEM}')
```

# Proposed fix:
It seems like `check_dipole(...)` only expects `(x,y,z)`. This function could be extended to also deal with `(x,y,z,azim,dip)`. Whether or not this is the full scope of the issue is unclear to me at this point.

**Comment by prisae** [comment]
Hi @TobiasGlaubach .

`dipole` only expects `(x, y, z)` and the parameter `ab` which defines the source configuration. `dipole` only works for point dipoles, aligned with the major axis. What you want is `bipole`, not `dipole`.

Here the two descriptions:
- `dipole`: https://empymod.readthedocs.io/en/stable/modeller.html#empymod.model.dipole
- `bipole`: https://empymod.readthedocs.io/en/stable/modeller.html#empymod.model.bipole

**Comment by prisae** [comment]
I just saw now that you actually combined two things in your `inpdat`, `azm`/`dip` with `ab`. The former is for `bipole`, the latter for `dipole`.

Have a look at the docs, and please let me know if there is something that is not clear. E.g., if the distinction between `dipole` and `bipole` is not clear (the naming of them is probably a bit unfortunate to start with, but too late to change that I fear...). I am pretty sure the docs could be improved, so I am happy about any constructive feedback!

**Comment by prisae** [comment]
Just opened #101.

Your use-case works as expected. You provide a wrong src/rec-definition for `dipole`, it fails with a warning that source and receiver are wrongly defined.

However, if you change in your example `empymod.dipole` to `empymod.bipole` it works without any warnings etc - but, it should warn that there is an unused keyword `ab` provided. This has to be improved.

Thanks again!

**Comment by prisae** [comment]
That is actually already implemented. If you use `empymod.bipole`, and keep `verb=1` (or anything > 0) then it would actually notify you
```
* WARNING :: Unused **kwargs: {'ab': 66}.
* WARNING :: Offsets < 0.001 m are set to 0.001 m!
```
So it works as expected for both, `empymod.dipole` (fails with a note on wrong src/rec definition) and `empymod.bipole` (warns about unused keyword).
