### ISSUE TITLE
analytical dipole strenght

### ISSUE THREAD

**Issue by jwittke** [empymod/empymod#25]
Hi,
is it possible to specify the strenght of analytical dipole source when using

`import empymod as epm`
` model = {'res': 1 / 3.2,  # Resistivity`
          `                 'freqtime': 1,  #`
`                 'signal': None,  # Frequency domain`
`                 'solution': 'dhs',  # Diffusive half-space solution`
`                 'verb': 1}  # Verbosity`
 
` field[:] = epm.analytical(ab=25, **model)`

Or is it set internally constant to 1A?

**Comment by prisae** [comment]
Hi Jan, thanks for your interest in empymod!

No, it is not possible. The analytical solution calculates the solution for an infinitesimal small dipole of unit strength. It is not set internally to 1A, there is simply no `strength`-parameter for `empymod.analytical`.

For the analytical fullspace solution there is a way: You could use `empymod.bipole`, providing a fullspace model and setting `xdirect=True`; this way `bipole` uses internally the analytical fullspace solution. But in this case you could provide a `strength`-parameter (and even source and receiver length, orientation, etc).

However, for the analytical, diffusive halfspace solution that is not possible. But in the end you only have to multiply the output by your source strength, and that's it.

```
import empymod as epm
model = {
    'src': [0, 0, 0],     # Source
    'rec': [5000, 0, 0],  # Receiver
    'res': 1 / 3.2,       # Resistivity (Ohm.m)
    'freqtime': 1,        # Frequency (Hz)
    'signal': None,       # Frequency domain
    'solution': 'dhs',    # Diffusive half-space solution
    'verb': 1             # Verbosity
}

strength = 250  # strength in A

field[:] = strength*epm.analytical(ab=22, **model)
```

Similarly, you could multiply it by source and receiver lengths.

**Please note** that the diffusive halfspace solution is only implemented for electric sources and receivers, hence for `ab=11, 12, 13, 21, 22, 23, 31, 32, 33`, so you cannot calculate the diffusive halfspace solution for `ab=25`. The diffusive halfspace solution is after **Slob, E., J. Hunziker, and W. A. Mulder, 2010**, *Green's tensors for the diffusive electric field in a VTI half-space*: PIER, 107, 1--20: doi: [10.2528/PIER10052807](http://doi.org/10.2528/PIER10052807), which only provides the solutions for electric source and receivers. If you need halfspace results for `ab=25` then you have to use the numerical solutions `dipole` or `bipole`. Again, with `bipole` you could define the source strength.

Hope that helps!
