### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'latex': 'latex'.

### ISSUE THREAD

**Issue by prisae** [empymod/empymod#4]
**Note:** *This is an issue I received per email. I reproduce it here so others  with the same issue might find the answer.*

Hi,

I have just started using python to run your empymod code because I want to run a simple GPR 2-layer model. I have used anaconda and set up the empymod from the prisae channel. I have `numpy` and `scipy` installed. However I get an error on the plotting in jupyter notebooks;

    FileNotFoundError: [Errno 2] No such file or directory: 'latex': 'latex'.

Can you give me any advice on how to find the 'latex' folder. I have done some searching on the web, but I have got nowhere.

Thank you

**Comment by prisae** [comment]
I use in some of the figures LaTeX for math symbols. It appears that you don't have LaTeX installed. Doesn't matter. Just remove the line where it says:

    mpl.rcParams['text.usetex'] = True

and then it should work.

Now, a word of caution. That `empymod` works for GPR is a very interesting fact, but not much more. It shows that the wavenumber-domain solution is exact for any frequency; there are some difficulties with the Hankel and the Fourier transforms at high frequencies, but that is another story (see [github.com/empymod/article-fdesign](https://github.com/empymod/article-fdesign)).

However, the strength of empymod is definitely in lower frequencies, such as CSEM. If you plan to do some serious GPR-modelling you might better start with another package, for instance:

- http://www.gprmax.com
- http://www.simpeg.xyz

Both are written in Python too. They do the calculation directly in the time-domain, and therefore do not face the issues with the Hankel- and Fourier transforms. Furthermore, both allow you to have 2D or 3D models, whereas `empymod` is restricted to layered models. But in GPR you often want to model 2D or 3D structures, such as pipes, tunnels, caves, etc.

Hope that helps!

**Comment by LuffyLuffy** [comment]
Thanks!
It really took a long while to install latex without root, and found that  still not working!
"mktexfmt [ERROR]: -user mode but path setup is -sys type, bailing out."
just don't use latex in the plot and it will help to offer a default font for plot and modify it by using some figure modified software!

**Comment by prisae** [comment]
Hi @LuffyLuffy, thanks for reporting. Which examples did you try to run? Because I don't think I use LaTeX any more in any of the updated examples of empymod: https://empymod.readthedocs.io/en/stable/examples/index.html

Where I do use LaTeX was in the publications. Mostly I wrote a comment that removing the line is just enough. E.g., in the notebooks of https://github.com/empymod/article-geo2017

```mpl.rcParams['text.usetex'] = True  # Comment this if you don't have LaTeX. You might have to adjust some strings.```

**Comment by LuffyLuffy** [comment]
> Hi @LuffyLuffy, thanks for reporting. Which examples did you try to run? Because I don't think I use LaTeX any more in any of the updated examples of empymod: https://empymod.readthedocs.io/en/stable/examples/index.html
> 
> Where I do use LaTeX was in the publications. Mostly I wrote a comment that removing the line is just enough. E.g., in the notebooks of https://github.com/empymod/article-geo2017
> 
> `mpl.rcParams['text.usetex'] = True # Comment this if you don't have LaTeX. You might have to adjust some strings.`

Actually, i found some drawing figure scripts with latex and want to use them and found this error, and I google a lot and found your comment here. 
Thanks for you sharing. Previously, I was trying so hard to install latex without root. But I failed to make it work. It's your hint that help me to solve the problem  and get the figure I want.  Thanks again.

**Comment by prisae** [comment]
Ah I see, it wasn't with empymod, it was just the same problem but with some other scripts. Glad I could help! And thanks for letting me know! Have a great day.
